experiment:
  backend: [pytorch]
  data_config:
    strategy: fixed
    train_path: ../data/{0}/Train.tsv
    validation_path: ../data/{0}/Val.tsv
    test_path: ../data/{0}/Test.tsv
    side_information:
      - dataloader: InteractionsTextualAttributes
        interactions_features: ../data/{0}/reviews/
        interactions: ../data/{0}/interactions.tsv
  dataset: Digital_Music
  top_k: 20
  evaluation:
    cutoffs: [20]
    simple_metrics: [Recall, MSE]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    external.RoGER:
      meta:
        hyper_opt_alg: grid
        verbose: True
        save_weights: False
        save_recs: False
        validation_rate: 1
        validation_metric: MSE
        restore: False
      epochs: 50
      batch_size: 128
      factors: [8, 16, 32]
      n_layers: [1, 2, 3, 4]
      lr: [0.0001, 0.0005, 0.001, 0.005, 0.01]
      seed: 123
      lambda: [0.0, 0.3, 0.7, 1.0]
      eps: [0.1, 0.01]
      l_ind: [0.000001, 0.00001, 0.0001]
      dense: (32,16,8)
      aggr: [sim, nn, att]