experiment:
  backend: [tensorflow, pytorch]
  data_config:
    strategy: fixed
    train_path: ../data/{0}/Train.tsv
    validation_path: ../data/{0}/Val.tsv
    test_path: ../data/{0}/Test.tsv
  dataset: Digital_Music
  top_k: 20
  evaluation:
    cutoffs: [20]
    simple_metrics: [Recall, MSE]
  gpu: 1
  external_models_path: ../external/models/__init__.py
  models:
#    external.MF:
#      meta:
#        hyper_opt_alg: grid
#        verbose: True
#        save_weights: False
#        save_recs: False
#        validation_rate: 1
#        validation_metric: MSE
#        restore: False
#      epochs: 50
#      batch_size: 128
#      factors: 8
#      lr: 0.0005
#      seed: 124
    external.NCF:
      meta:
        hyper_opt_alg: grid
        verbose: True
        save_weights: False
        save_recs: False
        validation_rate: 1
        validation_metric: MSE
        restore: False
      epochs: 50
      batch_size: 128
      factors: 16
      lr: 0.01
      dropout: 0.1
      dense_size: (32,16,8)
      seed: 123
#    external.GCMC:
#      meta:
#        save_recs: False
#        validation_metric: MSE
#        validation_rate: 1
#        verbose: True
#      epochs: 50
#      batch_size: 128
#      factors: 32
#      lr: 0.0005
#      n_conv: 1
#      n_dense: 1
#      relations: (1,2,3,4,5)
#      num_basis: 2
#      dropout: 0.1
#      acc: stack
#      seed: [456, 789, 101112, 131415]